/**
 * Popular UNAFFILIATED brokers (SEO coverage + neutrality).
 *
 * These are REAL, widely-searched brokers we hold NO affiliate deal with. They
 * are legitimate companies (NOT scams) — so none is `flagged` and none is
 * smeared. Each carries `unaffiliated: true`, NO affiliate link, and its page
 * states plainly that it is "not in our current top picks" while linking the
 * reader to our top-rated brokers. Purpose: rank for high-volume broker-name
 * searches that are currently under-served, and prove our neutrality by
 * covering brokers we do not earn from.
 *
 * DATA DISCIPLINE: every field is a publicly-known, stable fact about the
 * broker (regulator, founding year, platforms, headline account terms). Where a
 * figure varies by entity/account we pick a representative, defensible value and
 * keep the tone factual. Same accuracy bar as any affiliated page — no invented
 * licences (the CySEC/Fxcess mistake must never repeat). regulationScore uses
 * the same 1-5 scale: tier-one (FCA/ASIC/DFSA) lifts it; offshore-only caps it.
 */

import type { Broker, CountryCode } from "../brokers";

const EU_NORDIC: CountryCode[] = [
  "UK",
  "Netherlands",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
];

export const POPULAR_UNAFFILIATED: Broker[] = [
  {
    slug: "exness",
    name: "Exness",
    tagline: "High-volume broker known for instant withdrawals and high leverage.",
    regulators: ["FCA (UK)", "CySEC (Cyprus)", "FSCA (South Africa)", "FSA (Seychelles)"],
    regulationScore: 3,
    founded: 2008,
    minDeposit: 10,
    avgSpreadEurUsd: 0.6,
    commissionPerLot: 7,
    maxLeverage: 2000,
    platforms: ["MT4", "MT5", "WebTrader"],
    assetClasses: ["Forex", "Indices", "Commodities", "Crypto", "Stocks"],
    withdrawalDays: 1,
    demoAccount: true,
    negativeBalanceProtection: true,
    segregatedFunds: true,
    trustpilotRating: 3.9,
    trustpilotReviews: 22000,
    countriesServed: [...EU_NORDIC, "Other"],
    affiliateUrl: "",
    unaffiliated: true,
    lastVerified: "2026-08-04",
  },
  {
    slug: "xm",
    name: "XM",
    tagline: "Large, long-established broker with a big global client base.",
    regulators: ["ASIC (Australia)", "CySEC (Cyprus)", "DFSA (Dubai)", "FSC (Belize)"],
    regulationScore: 3,
    founded: 2009,
    minDeposit: 5,
    avgSpreadEurUsd: 0.6,
    commissionPerLot: 0,
    maxLeverage: 1000,
    platforms: ["MT4", "MT5"],
    assetClasses: ["Forex", "Indices", "Commodities", "Stocks", "Crypto"],
    withdrawalDays: 2,
    demoAccount: true,
    negativeBalanceProtection: true,
    segregatedFunds: true,
    trustpilotRating: 4.2,
    trustpilotReviews: 3600,
    countriesServed: [...EU_NORDIC, "Other"],
    affiliateUrl: "",
    unaffiliated: true,
    lastVerified: "2026-08-04",
  },
  {
    slug: "roboforex",
    name: "RoboForex",
    tagline: "Offshore broker with a wide instrument range and many account types.",
    regulators: ["FSC (Belize)"],
    regulationScore: 2,
    founded: 2009,
    minDeposit: 10,
    avgSpreadEurUsd: 0.5,
    commissionPerLot: 4,
    maxLeverage: 2000,
    platforms: ["MT4", "MT5", "cTrader"],
    assetClasses: ["Forex", "Indices", "Commodities", "Stocks", "Crypto"],
    withdrawalDays: 2,
    demoAccount: true,
    negativeBalanceProtection: true,
    segregatedFunds: true,
    trustpilotRating: 4.0,
    trustpilotReviews: 2400,
    countriesServed: [...EU_NORDIC, "Other"],
    affiliateUrl: "",
    unaffiliated: true,
    lastVerified: "2026-08-04",
  },
  {
    slug: "fbs",
    name: "FBS",
    tagline: "Popular retail broker in Asia with a low entry deposit.",
    regulators: ["ASIC (Australia)", "CySEC (Cyprus)", "FSC (Belize)"],
    regulationScore: 2,
    founded: 2009,
    minDeposit: 5,
    avgSpreadEurUsd: 0.7,
    commissionPerLot: 6,
    maxLeverage: 3000,
    platforms: ["MT4", "MT5"],
    assetClasses: ["Forex", "Indices", "Commodities", "Stocks"],
    withdrawalDays: 2,
    demoAccount: true,
    negativeBalanceProtection: true,
    segregatedFunds: true,
    trustpilotRating: 3.8,
    trustpilotReviews: 1900,
    countriesServed: [...EU_NORDIC, "Other"],
    affiliateUrl: "",
    unaffiliated: true,
    lastVerified: "2026-08-04",
  },
  {
    slug: "octafx",
    name: "OctaFX",
    tagline: "Offshore broker with a simple app and copy-trading features.",
    regulators: ["FSCA (South Africa)", "FSC (Mauritius)"],
    regulationScore: 2,
    founded: 2011,
    minDeposit: 25,
    avgSpreadEurUsd: 0.7,
    commissionPerLot: 0,
    maxLeverage: 500,
    platforms: ["MT4", "MT5", "WebTrader"],
    assetClasses: ["Forex", "Indices", "Commodities", "Crypto"],
    withdrawalDays: 3,
    demoAccount: true,
    negativeBalanceProtection: true,
    segregatedFunds: true,
    trustpilotRating: 4.1,
    trustpilotReviews: 2800,
    countriesServed: [...EU_NORDIC, "Other"],
    affiliateUrl: "",
    unaffiliated: true,
    lastVerified: "2026-08-04",
  },
  {
    slug: "ic-markets",
    name: "IC Markets",
    tagline: "High-volume ECN broker popular with scalpers and algo traders.",
    regulators: ["ASIC (Australia)", "CySEC (Cyprus)", "FSA (Seychelles)"],
    regulationScore: 4,
    founded: 2007,
    minDeposit: 200,
    avgSpreadEurUsd: 0.1,
    commissionPerLot: 7,
    maxLeverage: 500,
    platforms: ["MT4", "MT5", "cTrader"],
    assetClasses: ["Forex", "Indices", "Commodities", "Stocks", "Crypto", "Bonds"],
    withdrawalDays: 1,
    demoAccount: true,
    negativeBalanceProtection: true,
    segregatedFunds: true,
    trustpilotRating: 4.6,
    trustpilotReviews: 24000,
    countriesServed: [...EU_NORDIC, "Other"],
    affiliateUrl: "",
    unaffiliated: true,
    lastVerified: "2026-08-04",
  },
  {
    slug: "fxpro",
    name: "FxPro",
    tagline: "Established, well-regulated broker with multiple platforms.",
    regulators: ["FCA (UK)", "CySEC (Cyprus)", "FSCA (South Africa)", "SCB (Bahamas)"],
    regulationScore: 4,
    founded: 2006,
    minDeposit: 100,
    avgSpreadEurUsd: 0.4,
    commissionPerLot: 0,
    maxLeverage: 500,
    platforms: ["MT4", "MT5", "cTrader", "Proprietary"],
    assetClasses: ["Forex", "Indices", "Commodities", "Stocks", "Crypto"],
    withdrawalDays: 2,
    demoAccount: true,
    negativeBalanceProtection: true,
    segregatedFunds: true,
    trustpilotRating: 4.1,
    trustpilotReviews: 2100,
    countriesServed: [...EU_NORDIC, "Other"],
    affiliateUrl: "",
    unaffiliated: true,
    lastVerified: "2026-08-04",
  },
  {
    slug: "hfm",
    name: "HFM (HotForex)",
    tagline: "Multi-regulated broker, formerly branded HotForex.",
    regulators: ["FCA (UK)", "CySEC (Cyprus)", "DFSA (Dubai)", "FSCA (South Africa)", "FSC (Mauritius)"],
    regulationScore: 3,
    founded: 2010,
    minDeposit: 5,
    avgSpreadEurUsd: 0.5,
    commissionPerLot: 6,
    maxLeverage: 1000,
    platforms: ["MT4", "MT5"],
    assetClasses: ["Forex", "Indices", "Commodities", "Stocks", "Bonds"],
    withdrawalDays: 2,
    demoAccount: true,
    negativeBalanceProtection: true,
    segregatedFunds: true,
    trustpilotRating: 4.3,
    trustpilotReviews: 2600,
    countriesServed: [...EU_NORDIC, "Other"],
    affiliateUrl: "",
    unaffiliated: true,
    lastVerified: "2026-08-04",
  },
  {
    slug: "tickmill",
    name: "Tickmill",
    tagline: "Low-cost broker favoured for tight spreads and low commissions.",
    regulators: ["FCA (UK)", "CySEC (Cyprus)", "FSA (Seychelles)"],
    regulationScore: 4,
    founded: 2014,
    minDeposit: 100,
    avgSpreadEurUsd: 0.1,
    commissionPerLot: 4,
    maxLeverage: 500,
    platforms: ["MT4", "MT5"],
    assetClasses: ["Forex", "Indices", "Commodities", "Bonds"],
    withdrawalDays: 1,
    demoAccount: true,
    negativeBalanceProtection: true,
    segregatedFunds: true,
    trustpilotRating: 4.5,
    trustpilotReviews: 5200,
    countriesServed: [...EU_NORDIC, "Other"],
    affiliateUrl: "",
    unaffiliated: true,
    lastVerified: "2026-08-04",
  },
  {
    slug: "eightcap",
    name: "Eightcap",
    tagline: "Australian broker with strong crypto CFD coverage.",
    regulators: ["ASIC (Australia)", "FCA (UK)", "SCB (Bahamas)"],
    regulationScore: 4,
    founded: 2009,
    minDeposit: 100,
    avgSpreadEurUsd: 0.4,
    commissionPerLot: 7,
    maxLeverage: 500,
    platforms: ["MT4", "MT5", "WebTrader"],
    assetClasses: ["Forex", "Indices", "Commodities", "Stocks", "Crypto"],
    withdrawalDays: 2,
    demoAccount: true,
    negativeBalanceProtection: true,
    segregatedFunds: true,
    trustpilotRating: 4.4,
    trustpilotReviews: 1300,
    countriesServed: [...EU_NORDIC, "Other"],
    affiliateUrl: "",
    unaffiliated: true,
    lastVerified: "2026-08-04",
  },
];
